/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Decoder {
  constructor(dictionary?: Buffer | undefined | null)
  decode(data: Buffer): Promise<Buffer>
  decodeSync(data: Buffer): Buffer
}
export class Encoder {
  constructor(level: number, dictionary?: Buffer | undefined | null)
  encode(data: Buffer): Promise<Buffer>
  encodeSync(data: Buffer): Buffer
}
